MathJax.Hub.Config({
    TeX: {
        Macros: {
            dd: ["{\\text{d}#1\\,}",1],
            nouts: ["{n_{\\text{o}}}"],
            ints: ["{[\\![#1]\\!]}",1],
            outset: ["{\\ints{\\nouts}}"],
            N: ["{\\mathbb{N}}"],
            R: ["{\\mathbb{R}}"],
            Z: ["{\\mathbb{Z}}"],
            infsize: ["{z}"],
            infparties: ["{\\set{I}}"],
            infsources: ["{\\set{S}}"],
            infmarg: ["{\\set{A}}"],
            infmargg: ["{\\set{B}}"],
            netparties: ["{\\set{N}}"],
            infq: ["{q}"],
            infqs: ["{\\Delta_{\\infparties}}"],
            constraintlist: ["{\\mathcal{C}}"],
            injsets: ["{\\text{InjSets}}"],
            infconstraints: ["{\\text{InfCons}}"],
            parents: ["{\\text{Par}}"],
            targetp: ["{p}"],
            targetps: ["{\\Delta_{\\netparties}}"],
            set: ["{\\mathbf{#1}}",1],
            type: ["{t}"],
            infevent: "{\\omega}",
            events: ["{\\Omega_{#1}}",1],
            infevents: ["{\\events{\\infparties}}"],
            redinfevents: ["{\\tilde{\\Omega}_{\\infparties}}"],
            netevents: ["{\\events{\\netparties}}"],
            vecset: ["{V_{#1}}",1],
            alice: ["{\\text{A}}"],
            bob: ["{\\text{B}}"],
            charlie: ["{\\text{C}}"],
            symgroup: ["{\\text{Sym}(#1)}",1],
            shortsymgroup: ["{\\text{Sym}_{#1}}",1],
            act: ["{(#1\\hspace{2pt}{:}\\hspace{2pt}#2)}",2],
            actt: ["{[#1\\hspace{2pt}{:}\\hspace{2pt}#2]}",2],
            margperms: ["{\\text{Perm}_{#1}}",1],
            permutedmargs: ["{\\mathbb{P}_{#1}^{\\targetp}}",1],
            redpermutedmargs: ["{\\tilde{\\mathbb{P}}_{#1}^{\\constraintname,\\targetp}}",1],
            extract: ["{\\text{ext}(#1,#2)}",2],
            partysym: ["{\\tau}"],
            sourcesym: ["{\\xi}"],
            outsym: ["{\\sigma}"],
            fullgroup: ["{\\text{InfGrp}}"],
            partygroup : ["{\\text{PartyGrp}}"],
            outgroup: ["{\\text{OutGrp}}"],
            sourcegroup: ["{\\text{SrcGrp}}"],
            distrgroup: ["{\\mathbb{G}^\\targetp}"],
            constraintname: ["{c}"],
            marggroup: ["{\\mathbb{G}^{\\constraintname,\\targetp}}"],
            fullsymexpl: ["{(\\sourcesym,\\partysym,\\outsym)}"],
            inner: ["{\\langle#1,#2\\rangle}", 2],
            quovec: ["{f}"],
            totconstraintmap: ["{K^{\\constraintlist,\\targetp}}"],
            totconstraintmapelem: ["{K^{\\constraintname,\\targetp}}"],
            quovecspace: ["{\\tilde{V}_{#1}^{\\constraintname,\\targetp}}", 1],
            totquovecspace: ["{\\text{ConsSpace}(\\constraintlist,\\targetp)}"],
            detdistr: ["{\\delta^{#1}}", 1],
            margperm: ["{\\varphi}"],
            altquovecembed: ["{\\text{G}_{#1}^{\\constraintname,\\targetp}}", 1],
            vecset: ["{V_{#1}}", 1],
            repr: ["{\\lfloor#1\\rfloor}", 1],
            gid: ["{\\text{id}}"],
            id: ["{1_{#1}}",1],
            consscale: ["{K}"],
            scaletot: ["{K_{\\text{tot}}^{\\constraintlist,\\targetp}}"],
            minnorm: ["{d}"],
            Bigsetst: ["\\;\\Big|\\;"],
            activeset: ["\\mathcal{S}"],
            conv: ["\\text{conv}"],
            lVert: ["|\\hspace{-1pt}|"],
            norm: ["\\lVert#1\\lVert", 1],
            st: [":\ "],
        }
    }
});
